[package]
name = "hmmer-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebAssembly bindings for HMMER"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.118"
hmmer-core = { path = "../hmmer-core" }
hmmer-io = { path = "../hmmer-io" }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
