[workspace]
members = [
  "crispr-cas-finder-core",
  "crispr-cas-finder-cli",
  "crispr-cas-finder-wasm",
  "hmmer-core",
  "hmmer-io",
]
exclude = ["crispr-cas-finder-python", "hmmer-py", "openevolve/bench"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "GPL-3.0-or-later"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true
debug-assertions = false
overflow-checks = false

[profile.profiling]
inherits = "release"
debug = true

[profile.test]
opt-level = 3
