[package]
name = "crispr-cas-finder-core"
version = "0.1.0"
edition = "2024"
description = "Core library for CRISPR-Cas detection"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
bio = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
orphos-core = "0.3.0"
hmmer-core = { path = "../hmmer-core" }
hmmer-io = { path = "../hmmer-io" }
rayon = "1.11"
