[package]
name = "crispr-cas-finder-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Core library for CRISPR-Cas detection"
license = "GPL-3.0-or-later"
repository = "https://github.com/FullHuman/crispr-cas-finder"
readme = "../README.md"

[features]
hmmer-serde = []

[dependencies]
anyhow = "1"
bio = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
quick-xml = "0.41.0"
orphos-core = "0.3.0"
bitflags = "2"
thiserror = "2"
ndarray = "0.17"
rayon = "1.11"

[dev-dependencies]
tempfile = "3"
