[package]
name = "crispr-cas-finder-python"
version = "0.1.0"
edition = "2024"
description = "Python bindings for crispr-cas-finder-core"
license = "GPL-3.0-or-later"

[lib]
name = "crispr_cas_finder"
crate-type = ["cdylib"]

[dependencies]
crispr-cas-finder-core = { path = "../crispr-cas-finder-core" }
pyo3 = { version = "0.29.0", features = ["extension-module"] }
