use hmmer_core::{
    alphabet::Alphabet,
    background::BackgroundModel,
    config::SearchMode,
    modelconfig,
    pipeline::search::{CapacityHints, SearchOutcome, SearchPlan, SearchQuery},
    profile::Profile,
    sequence::DigitalSequence,
};
use hmmer_io::HmmFile;

/// Oracle values generated by HMMER 3.4 `hmmsearch` for TIGR01868 against
/// E. coli Cas5 (CP014688.1_298).
#[test]
fn cas5_domain_null2_and_oa_match_hmmer_3_4() {
    let profile_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../crispr-cas-finder-cli/data/CasFinder-2.0.3/CASprofiles-2.0.3/Cas5_0_IE.hmm");
    let mut hmm_file = HmmFile::open(profile_path.to_str().unwrap(), None).unwrap();
    let (alphabet, hmm) = hmm_file.read().unwrap();
    let sequence = b"MRSYLILRLAGPMQAWGQPTFEGTRPTGRFPTRSGLLGLLGACLGIQRDDTSSLQALSESVQFAVRCDELILDDRRVSVTGLRDYHTVLGAREDYRGLKSHETIQTWREYLCDASFTVALWLTPHATMVISELEKAVLKPRYTPYLGRRSCPLTHPLFLGTCQASDPQKALLNYEPVGGDIYSEESVTGHHLKFTARDEPMITLPRQFASREWYVIKGGMDVSQ";
    let target = DigitalSequence::from_bytes("CP014688.1_298", "", sequence, &alphabet);

    let background = BackgroundModel::new(&Alphabet::amino());
    let mut profile = Profile::new(hmm.num_nodes, &alphabet);
    modelconfig::profile_config(
        &hmm,
        &background,
        &mut profile,
        target.len(),
        SearchMode::Local,
    );
    let query = SearchQuery::from_configured_profile(profile, background).unwrap();
    let plan = SearchPlan::builder(query).build().unwrap();
    let mut worker = plan
        .spawn_worker(CapacityHints {
            target_length: target.len(),
        })
        .unwrap();

    let report = worker.search(&target).unwrap();
    let SearchOutcome::Hit(hit) = report.outcome else {
        panic!("HMMER 3.4 reports a hit for the Cas5 oracle target");
    };
    assert_eq!(hit.domains.len(), 1);
    assert!(
        (hit.score - 288.6).abs() < 0.15,
        "sequence score={}",
        hit.score
    );

    let domain = &hit.domains[0];
    assert!(
        (domain.bitscore - 288.4).abs() < 0.15,
        "domain score={}",
        domain.bitscore
    );
    assert!(domain.domain_bias / std::f32::consts::LN_2 < 0.05);
    assert_eq!((domain.hmm_from, domain.hmm_to), (1, 230));
    assert_eq!((domain.alignment_start, domain.alignment_end), (3, 216));
    assert_eq!((domain.envelope_start, domain.envelope_end), (3, 216));
    let envelope_length = domain.envelope_end - domain.envelope_start + 1;
    assert!(domain.optimal_accuracy_score / envelope_length as f32 > 0.98);
}
