[package]
name = "crisprcas-python"
version = "0.1.0"
edition = "2024"
description = "Python bindings for crisprcas-core"
license = "GPL-3.0-or-later"

[lib]
name = "crispr_cas_finder"
crate-type = ["cdylib"]

[dependencies]
crisprcas-core = { path = "../crisprcas-core" }
pyo3 = { version = "0.27.1", features = ["extension-module"] }
serde_json = "1.0"
